"""Build NB3: RL Test Flow — Steps 8-13 (Final + Curriculum + Plots + Export)."""
import json
from pathlib import Path

def cc(src): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":src}
def mc(src): return {"cell_type":"markdown","metadata":{},"source":src}

cells = []

cells.append(mc(
    "# RL Test Flow Optimization — Notebook 3 of 3: Final + Plots + Export\n\n"
    "**Prerequisites**: `rl-stage1-results` AND `rl-stage2-results` datasets added as inputs.\n"
    "**RL training device**: CPU (intentional for SB3 MLP workloads).\n\n"
    "| Step | Description | Est. Time |\n"
    "|------|-------------|----------|\n"
    "| 8 | Final training: best algo + HPO params × 1M steps | ~3-4 h |\n"
    "| 9 | Curriculum: n_tests=[10,50,200] × 200K each | ~1-2 h |\n"
    "| 10 | Learning curves + reward distribution | ~5 min |\n"
    "| 11 | Coverage histogram + cost efficiency | ~5 min |\n"
    "| 12 | Heatmap + comprehensive summary table | ~5 min |\n"
    "| 13 | ZIP all models + export | ~5 min |\n"
))

# Reinstall + load NB2 results
cells.append(mc("## Step 0: Reinstall + Load All Results"))
cells.append(cc(
    "import subprocess, sys, os, json\n"
    "subprocess.run(['pip', 'install', '-q',\n"
    "    'stable-baselines3[extra]', 'sb3-contrib', 'gymnasium',\n"
    "    'optuna', 'mlflow', 'pyarrow', 'matplotlib', 'seaborn', 'numpy', 'torch'], check=True)\n\n"
    "!rm -rf rl-test-flow-optimization\n"
    "!git clone https://github.com/rajendarmuddasani/rl-test-flow-optimization.git\n"
    "os.chdir('rl-test-flow-optimization')\n"
    "sys.path.insert(0, '.')\n\n"
    "import torch, numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns\n"
    "print(f'GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"NONE — not required for this run\"}')\n"
    "print('RL train device: cpu (forced intentionally for SB3 MlpPolicy)')\n\n"
    "NB2_PATH = '/kaggle/input/rl-stage2-results/stage2_results.json'\n"
    "with open(NB2_PATH) as f:\n"
    "    nb2 = json.load(f)\n\n"
    "baseline_results  = nb2['baselines']\n"
    "stage1_results    = nb2['stage1']\n"
    "stage2_results    = nb2['stage2']\n"
    "hpo_result        = nb2['hpo']\n"
    "top2_algos        = nb2['top2_algos']\n"
    "best_algo         = nb2['best_algo']\n"
    "best_bl           = nb2['best_base_reward']\n"
    "best_params       = nb2['best_params']\n"
    "baseline_df       = pd.DataFrame(baseline_results).T\n"
    "stage1_df         = pd.DataFrame(stage1_results).T\n\n"
    "print(f'All results loaded. Best algo: {best_algo} with params:')\n"
    "for k, v in best_params.items(): print(f'  {k}: {v}')\n"
))

# Step 8: Final training
cells.append(mc(
    "## Step 8: Final Training — 1M Steps with Best Config\n\n"
    "1 million timesteps is the production-grade benchmark for this environment size.\n"
    "Using the best algorithm and HPO-tuned hyperparameters from NB2."
))
cells.append(cc(
    "import time as _time\n"
    "from src.environment import TestFlowEnv\n"
    "from src.agent import ALGO_REGISTRY, evaluate_trained_model\n"
    "from pathlib import Path\n\n"
    "FINAL_STEPS = 1_000_000\n"
    "SAVE_DIR3 = Path('/kaggle/working/rl_stage3')\n"
    "SAVE_DIR3.mkdir(parents=True, exist_ok=True)\n\n"
    "print(f'Final Training: {FINAL_STEPS:,} steps | algo={best_algo}')\n"
    "print(f'Params: {best_params}')\n"
    "print('=' * 70)\n\n"
    "env = TestFlowEnv(n_tests=200, cost_budget=50.0, time_budget=120.0)\n"
    "train_fn = ALGO_REGISTRY[best_algo]\n"
    "t0 = _time.time()\n"
    "final_model = train_fn(\n"
    "    env,\n"
    "    total_timesteps=FINAL_STEPS,\n"
    "    output_dir=str(SAVE_DIR3 / 'final_model'),\n"
    "    seed=42,\n"
    "    **{k: v for k, v in best_params.items() if k not in ['net_arch']},\n"
    ")\n"
    "final_train_time = _time.time() - t0\n\n"
    "final_metrics = evaluate_trained_model(env, final_model, n_episodes=1000)\n"
    "print(f'\\nFinal Model (1M steps, 1000 eval episodes):')\n"
    "print(f'  Mean Reward:    {final_metrics[\"mean_reward\"]:+.2f}')\n"
    "print(f'  Std Reward:     {final_metrics[\"std_reward\"]:+.2f}')\n"
    "print(f'  Accuracy:       {final_metrics[\"accuracy\"]*100:.1f}%')\n"
    "print(f'  Defect Rate:    {final_metrics.get(\"defect_escape_rate\", 0)*100:.2f}%')\n"
    "print(f'  Train Time:     {final_train_time/3600:.2f}h')\n"
    "print(f'  vs Baseline:   +{final_metrics[\"mean_reward\"] - best_bl:.2f} improvement')\n"
))

# Step 9: Curriculum
cells.append(mc(
    "## Step 9: Curriculum Learning — Complexity Ramp [10 → 50 → 200 tests]\n\n"
    "Progressive complexity training: start with easy (10 tests), grow to full scale (200).\n"
    "This is the same principle used in AlphaGo, GPT curriculum, and AMD test chip triage."
))
cells.append(cc(
    "curriculum_results = {}\n"
    "CURR_STEPS = 200_000  # per stage\n"
    "STAGES = [10, 50, 200]\n\n"
    "print(f'Curriculum: stages={STAGES}, steps_per_stage={CURR_STEPS:,}')\n"
    "print('=' * 70)\n\n"
    "for n_tests in STAGES:\n"
    "    print(f'\\n>>> Stage n_tests={n_tests}')\n"
    "    env = TestFlowEnv(n_tests=n_tests, cost_budget=50.0, time_budget=120.0)\n"
    "    t0 = _time.time()\n"
    "    model = train_fn(\n"
    "        env,\n"
    "        total_timesteps=CURR_STEPS,\n"
    "        output_dir=str(SAVE_DIR3 / f'curriculum_{n_tests}'),\n"
    "        seed=42,\n"
    "    )\n"
    "    elapsed = _time.time() - t0\n"
    "    metrics = evaluate_trained_model(env, model, n_episodes=200)\n"
    "    curriculum_results[n_tests] = {**metrics, 'train_time_sec': round(elapsed, 1)}\n"
    "    print(f'  reward={metrics[\"mean_reward\"]:+.2f} | acc={metrics[\"accuracy\"]*100:.1f}% | {elapsed/60:.1f}m')\n\n"
    "print('\\nCurriculum complete:', curriculum_results.keys())\n"
))

# Step 10: Learning curves
cells.append(mc("## Step 10: Learning Curves + Reward Distribution"))
cells.append(cc(
    "import matplotlib.pyplot as plt, matplotlib.gridspec as gridspec\n\n"
    "# Reconstruct stage2 seed data for plotting\n"
    "fig = plt.figure(figsize=(20, 14))\n"
    "gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.4, wspace=0.35)\n\n"
    "# Panel A: Stage-1 comparison bars\n"
    "ax0 = fig.add_subplot(gs[0, 0])\n"
    "algos_s1 = list(stage1_results.keys())\n"
    "means_s1 = [stage1_results[a]['mean_reward'] for a in algos_s1]\n"
    "accs_s1  = [stage1_results[a]['accuracy']    for a in algos_s1]\n"
    "x = np.arange(len(algos_s1))\n"
    "bars = ax0.bar(x, means_s1, color=['#2ECC71','#3498DB','#E74C3C','#9B59B6'])\n"
    "ax0.axhline(best_bl, color='black', linestyle='--', linewidth=2, label=f'Baseline ({best_bl:.1f})')\n"
    "ax0.set_xticks(x); ax0.set_xticklabels([a.upper() for a in algos_s1], rotation=45, ha='right')\n"
    "ax0.set_title('Stage-1 Rewards (200K steps)', fontsize=12, fontweight='bold')\n"
    "ax0.set_ylabel('Mean Reward'); ax0.legend()\n"
    "for bar, m in zip(bars, means_s1): ax0.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3, f'{m:.1f}', ha='center', fontsize=8)\n\n"
    "# Panel B: Stage-2 seed stability\n"
    "ax1 = fig.add_subplot(gs[0, 1])\n"
    "colors = ['#2ECC71', '#E74C3C']\n"
    "for i, algo in enumerate(top2_algos):\n"
    "    rewards = [m['mean_reward'] for m in stage2_results[algo]]\n"
    "    ax1.boxplot(rewards, positions=[i+1], widths=0.5, patch_artist=True,\n"
    "                boxprops=dict(facecolor=colors[i], alpha=0.7))\n"
    "ax1.set_xticks([1, 2]); ax1.set_xticklabels([a.upper() for a in top2_algos], rotation=45)\n"
    "ax1.axhline(best_bl, color='black', linestyle='--', linewidth=2)\n"
    "ax1.set_title('Stage-2 Seed Stability (500K × 3 seeds)', fontsize=12, fontweight='bold')\n"
    "ax1.set_ylabel('Reward per Seed')\n\n"
    "# Panel C: Curriculum progression\n"
    "ax2 = fig.add_subplot(gs[0, 2])\n"
    "curr_n = list(curriculum_results.keys())\n"
    "curr_r = [curriculum_results[n]['mean_reward'] for n in curr_n]\n"
    "curr_a = [curriculum_results[n]['accuracy']    for n in curr_n]\n"
    "ax2.plot(curr_n, curr_r, 'o-', color='#3498DB', linewidth=2.5, markersize=8, label='Reward')\n"
    "ax2b = ax2.twinx()\n"
    "ax2b.plot(curr_n, curr_a, 's--', color='#E74C3C', linewidth=2, markersize=8, label='Accuracy')\n"
    "ax2.set_xlabel('Number of Tests (Curriculum Stage)'); ax2.set_ylabel('Mean Reward', color='#3498DB')\n"
    "ax2b.set_ylabel('Accuracy', color='#E74C3C')\n"
    "ax2.set_title('Curriculum Learning Progression', fontsize=12, fontweight='bold')\n"
    "ax2.legend(loc='upper left'); ax2b.legend(loc='upper right')\n\n"
    "# Panel D: HPO optimization history\n"
    "ax3 = fig.add_subplot(gs[1, 0])\n"
    "if 'trial_values' in hpo_result:\n"
    "    vals = hpo_result['trial_values']\n"
    "    best_so_far = [max(vals[:i+1]) for i in range(len(vals))]\n"
    "    ax3.plot(vals, alpha=0.5, color='gray', linewidth=1, label='Trial reward')\n"
    "    ax3.plot(best_so_far, color='#E74C3C', linewidth=2.5, label='Best so far')\n"
    "    ax3.set_xlabel('Trial #'); ax3.set_ylabel('Reward')\n"
    "    ax3.set_title('Optuna HPO Convergence', fontsize=12, fontweight='bold')\n"
    "    ax3.legend()\n"
    "else:\n"
    "    ax3.text(0.5, 0.5, 'HPO trial history\\nnot serialized', ha='center', va='center', transform=ax3.transAxes)\n"
    "    ax3.set_title('Optuna HPO Convergence', fontsize=12, fontweight='bold')\n\n"
    "# Panel E: All stages comparison radar-bar\n"
    "ax4 = fig.add_subplot(gs[1, 1])\n"
    "categories = ['Baseline', 'Stage-1\\nbest', 'Stage-2\\nbest', 'Final\\n1M', 'Curriculum\\n200t']\n"
    "s2_best = max(max(m['mean_reward'] for m in v) for v in stage2_results.values())\n"
    "values  = [\n"
    "    best_bl,\n"
    "    stage1_df['mean_reward'].max() if hasattr(stage1_df, 'columns') else max(stage1_results[a]['mean_reward'] for a in stage1_results),\n"
    "    s2_best,\n"
    "    final_metrics['mean_reward'],\n"
    "    curriculum_results[200]['mean_reward'],\n"
    "]\n"
    "clrs = ['#7F8C8D','#5DADE2','#2ECC71','#F39C12','#9B59B6']\n"
    "ax4.bar(categories, values, color=clrs, edgecolor='white', linewidth=1.5)\n"
    "ax4.set_title('Reward Progression by Stage', fontsize=12, fontweight='bold')\n"
    "ax4.set_ylabel('Mean Reward')\n"
    "for i, v in enumerate(values): ax4.text(i, v + 0.2, f'{v:.1f}', ha='center', fontsize=9, fontweight='bold')\n\n"
    "# Panel F: Cost efficiency vs reward scatter\n"
    "ax5 = fig.add_subplot(gs[1, 2])\n"
    "all_metrics = {\n"
    "    **{k: v for k, v in baseline_results.items()},\n"
    "    **{k+'_s1': v for k, v in stage1_results.items()},\n"
    "    'Final_1M': final_metrics,\n"
    "}\n"
    "if all(hasattr(v, 'get') and 'mean_cost_per_ep' in v for v in all_metrics.values()):\n"
    "    costs = [v.get('mean_cost_per_ep', 0) for v in all_metrics.values()]\n"
    "    rews  = [v.get('mean_reward', 0) for v in all_metrics.values()]\n"
    "    ax5.scatter(costs, rews, alpha=0.8, s=100)\n"
    "    for label, c, r in zip(all_metrics.keys(), costs, rews):\n"
    "        ax5.annotate(label, (c, r), fontsize=7, xytext=(3, 3), textcoords='offset points')\n"
    "    ax5.set_xlabel('Mean Cost/Episode'); ax5.set_ylabel('Mean Reward')\n"
    "else:\n"
    "    ax5.text(0.5, 0.5, 'Cost-efficiency data\\nnot available in metrics', ha='center', va='center', transform=ax5.transAxes)\n"
    "ax5.set_title('Cost Efficiency vs Reward', fontsize=12, fontweight='bold')\n\n"
    "fig.suptitle('RL Test Flow Optimization — Complete Results Summary', fontsize=15, fontweight='bold', y=1.01)\n"
    "plt.savefig(str(SAVE_DIR3 / 'all_results_overview.png'), bbox_inches='tight', dpi=150)\n"
    "plt.show()\n"
    "print('Panel saved: all_results_overview.png')\n"
))

# Step 11: Histograms
cells.append(mc("## Step 11: Reward Distribution Histograms (1000 episodes)"))
cells.append(cc(
    "from src.agent import evaluate_trained_model_detailed\n\n"
    "# get per-episode detail for final model\n"
    "try:\n"
    "    detail = evaluate_trained_model_detailed(env, final_model, n_episodes=1000)\n"
    "    epi_rewards = detail['episode_rewards']\n"
    "    epi_costs   = detail.get('episode_costs', [])\n"
    "    epi_defects = detail.get('defect_escapes', [])\n"
    "except Exception:\n"
    "    # fallback: quick manual rollout\n"
    "    epi_rewards, epi_costs = [], []\n"
    "    obs, _  = env.reset()\n"
    "    for _ in range(1000):\n"
    "        step_rew = 0\n"
    "        done = False\n"
    "        while not done:\n"
    "            action, _ = final_model.predict(obs, deterministic=True)\n"
    "            obs, rew, done, trunc, info = env.step(int(action))\n"
    "            step_rew += rew\n"
    "            if done or trunc:\n"
    "                epi_rewards.append(step_rew); epi_costs.append(info.get('cost_spent', 0))\n"
    "                obs, _ = env.reset(); step_rew = 0; done = False; break\n\n"
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n\n"
    "axes[0].hist(epi_rewards, bins=50, color='#3498DB', edgecolor='white', linewidth=0.5)\n"
    "axes[0].axvline(float(np.mean(epi_rewards)), color='red', linewidth=2, label=f'Mean: {np.mean(epi_rewards):.2f}')\n"
    "axes[0].axvline(best_bl, color='black', linewidth=2, linestyle='--', label=f'Baseline: {best_bl:.2f}')\n"
    "axes[0].set_xlabel('Episode Reward'); axes[0].set_ylabel('Count')\n"
    "axes[0].set_title('Final Model (1M steps) — Reward Distribution\\n1000 episodes', fontsize=11, fontweight='bold')\n"
    "axes[0].legend()\n\n"
    "if epi_costs:\n"
    "    axes[1].hist(epi_costs, bins=40, color='#2ECC71', edgecolor='white', linewidth=0.5)\n"
    "    axes[1].axvline(float(np.mean(epi_costs)), color='red', linewidth=2, label=f'Mean: {np.mean(epi_costs):.1f}')\n"
    "    axes[1].set_xlabel('Cost Spent per Episode'); axes[1].set_ylabel('Count')\n"
    "    axes[1].set_title('Cost Budget Usage Distribution', fontsize=11, fontweight='bold')\n"
    "    axes[1].legend()\n"
    "else:\n"
    "    axes[1].text(0.5, 0.5, 'Cost data unavailable', ha='center', va='center', transform=axes[1].transAxes)\n\n"
    "# Stage comparison histograms overlay\n"
    "bl_reward = [best_bl] * 100  # approximate\n"
    "axes[2].hist(epi_rewards, bins=40, alpha=0.7, color='#3498DB', label=f'Final 1M (μ={np.mean(epi_rewards):.1f})')\n"
    "for algo in top2_algos:\n"
    "    seeds_r = [m['mean_reward'] for m in stage2_results[algo]]\n"
    "    axes[2].axvline(np.mean(seeds_r), linewidth=2, linestyle='--', label=f'{algo.upper()} 500K (μ={np.mean(seeds_r):.1f})')\n"
    "axes[2].axvline(best_bl, color='black', linewidth=2.5, linestyle=':', label=f'Baseline ({best_bl:.1f})')\n"
    "axes[2].set_xlabel('Episode Reward'); axes[2].set_ylabel('Count')\n"
    "axes[2].set_title('Comparison: Final vs Stage-2 vs Baseline', fontsize=11, fontweight='bold')\n"
    "axes[2].legend(fontsize=8)\n\n"
    "plt.tight_layout()\n"
    "plt.savefig(str(SAVE_DIR3 / 'reward_histograms.png'), bbox_inches='tight', dpi=150)\n"
    "plt.show()\n"
    "print('Saved: reward_histograms.png')\n"
))

# Step 12: Heatmap + summary table
cells.append(mc("## Step 12: Algorithm Heatmap + Comprehensive Summary Table"))
cells.append(cc(
    "# Comprehensive metrics heatmap\n"
    "stage1_df_full = pd.DataFrame(stage1_results).T.apply(pd.to_numeric, errors='coerce')\n"
    "stage1_df_full['stage'] = 'Stage-1 (200K)'\n\n"
    "stage2_df_list = []\n"
    "for algo, seeds in stage2_results.items():\n"
    "    for m in seeds:\n"
    "        row = {k: float(v) if isinstance(v, (int, float)) else v for k, v in m.items()}\n"
    "        row['algo'] = algo; row['stage'] = 'Stage-2 (500K)'\n"
    "        stage2_df_list.append(row)\n"
    "stage2_df_full = pd.DataFrame(stage2_df_list)\n\n"
    "# Heatmap of stage1 metric matrix\n"
    "metric_cols = [c for c in stage1_df_full.columns if c not in ['stage'] and stage1_df_full[c].dtype in [float, 'float64']]\n"
    "if metric_cols:\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(18, 6))\n"
    "    hm_data = stage1_df_full[metric_cols].apply(pd.to_numeric, errors='coerce').dropna(axis=1)\n"
    "    if not hm_data.empty:\n"
    "        normed = (hm_data - hm_data.min()) / (hm_data.max() - hm_data.min() + 1e-9)\n"
    "        sns.heatmap(normed.T, annot=hm_data.T.round(3), fmt='g', cmap='YlGnBu',\n"
    "                    ax=axes[0], cbar_kws={'label': 'Normalized [0-1)'}, linewidths=0.5)\n"
    "        axes[0].set_title('Stage-1 Metric Heatmap (normalized)', fontsize=12, fontweight='bold')\n"
    "    else:\n"
    "        axes[0].text(0.5, 0.5, 'No numeric metrics in stage1', ha='center', va='center', transform=axes[0].transAxes)\n\n"
    "    # Comprehensive summary table\n"
    "    rows = []\n"
    "    for name, r in baseline_results.items():\n"
    "        rows.append({'Method': name, 'Stage': 'Baseline', 'Mean Reward': r.get('mean_reward',0),\n"
    "                     'Std Reward': r.get('std_reward',0), 'Accuracy': r.get('accuracy',0), 'Steps': 0})\n"
    "    for name, r in stage1_results.items():\n"
    "        rows.append({'Method': name, 'Stage': 'Stage-1', 'Mean Reward': r.get('mean_reward',0),\n"
    "                     'Std Reward': r.get('std_reward',0), 'Accuracy': r.get('accuracy',0), 'Steps': 200_000})\n"
    "    for algo, seeds in stage2_results.items():\n"
    "        rews = [m.get('mean_reward',0) for m in seeds]; accs = [m.get('accuracy',0) for m in seeds]\n"
    "        rows.append({'Method': algo+'(3-seed)', 'Stage': 'Stage-2', 'Mean Reward': float(np.mean(rews)),\n"
    "                     'Std Reward': float(np.std(rews)), 'Accuracy': float(np.mean(accs)), 'Steps': 500_000})\n"
    "    rows.append({'Method': best_algo+'(HPO)', 'Stage': 'Final', 'Mean Reward': final_metrics.get('mean_reward',0),\n"
    "                 'Std Reward': final_metrics.get('std_reward',0), 'Accuracy': final_metrics.get('accuracy',0), 'Steps': 1_000_000})\n"
    "    summary_df = pd.DataFrame(rows)\n"
    "    summary_df['Mean Reward'] = summary_df['Mean Reward'].round(2)\n"
    "    summary_df['Std Reward']  = summary_df['Std Reward'].round(3)\n"
    "    summary_df['Accuracy']    = summary_df['Accuracy'].round(3)\n"
    "    print('\\n=== COMPREHENSIVE SUMMARY TABLE ===' )\n"
    "    print(summary_df.to_string(index=False))\n"
    "    summary_df.to_csv(str(SAVE_DIR3 / 'comprehensive_summary.csv'), index=False)\n\n"
    "    axes[1].axis('off')\n"
    "    tbl = axes[1].table(cellText=summary_df.values, colLabels=summary_df.columns,\n"
    "                        cellLoc='center', loc='center', bbox=[0,0,1,1])\n"
    "    tbl.auto_set_font_size(False); tbl.set_fontsize(8)\n"
    "    axes[1].set_title('Comprehensive Summary Table', fontsize=12, fontweight='bold', pad=20)\n\n"
    "    plt.tight_layout()\n"
    "    plt.savefig(str(SAVE_DIR3 / 'heatmap_and_table.png'), bbox_inches='tight', dpi=150)\n"
    "    plt.show()\n"
    "    print('Saved: heatmap_and_table.png')\n"
    "else:\n"
    "    print('Skipping heatmap — no numeric metric columns found')\n"
))

# Step 13: Export
cells.append(mc("## Step 13: ZIP All Models + Export to /kaggle/working/"))
cells.append(cc(
    "import zipfile, hashlib, datetime\n\n"
    "zip_path = SAVE_DIR3 / 'rl_test_flow_final_models.zip'\n"
    "with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:\n"
    "    for ff in sorted(SAVE_DIR3.rglob('*')):\n"
    "        if ff.is_file() and not ff.name.endswith('.zip'):\n"
    "            zf.write(ff, ff.relative_to(SAVE_DIR3))\n\n"
    "zip_sha = hashlib.md5(zip_path.read_bytes()).hexdigest()\n\n"
    "print('=== NB3 FINAL ARTIFACTS ===')\n"
    "total = 0\n"
    "for ff in sorted(SAVE_DIR3.rglob('*')):\n"
    "    if ff.is_file():\n"
    "        print(f'  {str(ff.relative_to(SAVE_DIR3)):60s} {ff.stat().st_size/1e3:7.0f} KB')\n"
    "        total += ff.stat().st_size\n"
    "print(f'\\nTotal output: {total/1e6:.1f} MB')\n"
    "print(f'ZIP: {zip_path.name} | MD5: {zip_sha}')\n\n"
    "# Print final metrics card\n"
    "print('\\n' + '='*60)\n"
    "print('FINAL PERFORMANCE CARD')\n"
    "print('='*60)\n"
    "print(f'  Algorithm:         {best_algo.upper()} + Optuna HPO')\n"
    "print(f'  Timesteps:         1,000,000')\n"
    "print(f'  Mean Reward:       {final_metrics[\"mean_reward\"]:+.2f}')\n"
    "print(f'  Std Reward:        {final_metrics[\"std_reward\"]:+.2f}')\n"
    "print(f'  Accuracy:          {final_metrics[\"accuracy\"]*100:.1f}%')\n"
    "print(f'  Baseline (best):   {best_bl:+.2f}')\n"
    "print(f'  Improvement:       +{final_metrics[\"mean_reward\"]-best_bl:.2f}')\n"
    "print(f'  Date:              {datetime.date.today()}')\n"
    "print('='*60)\n"
    "print('COMPLETE — Download output as Kaggle Dataset for future use')\n"
))

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
    },
    "nbformat": 4, "nbformat_minor": 5,
}

out = Path('/Users/rajendarmuddasani/AIML/58_End2End/projects/rl-test-flow-optimization/notebooks/train_rl_kaggle_nb3.ipynb')
with open(out, 'w') as f:
    json.dump(nb, f, indent=1)
with open(out) as f:
    loaded = json.load(f)
print(f"NB3: {out.stat().st_size:,} bytes | {len(loaded['cells'])} cells | valid JSON ✓")
